name: 'Prefect Blocks Quickstart'
description: 'Deploy CloudRunJob and GitHub blocks for serverless containerized execution'
branding:
  icon: cloud
  color: blue
inputs:
  prefect_api_key:
    description: 'Prefect Cloud API key'
    required: true
  prefect_api_url:
    description: 'Prefect Cloud API URL'
    required: true
  block_name:
    description: 'Name of the GitHub, CloudRunJob and GcpCredentials blocks'
    required: false
    default: "default"
  image_uri:
    description: 'Name of the AR image URI'
    required: true
    default: "us-east1-docker.pkg.dev/prefect-community/prefect/deployments:latest"
  region:
    description: GCP region
    required: true
    default: 'us-east1'
  python_version:
    description: 'Python version'
    required: false
    default: "3.10"  # the latest Prefect 2 version is used by default
  install_command:
    description: 'Can be set to e.g. pip install -r requirements.txt'
    required: false
    default: "pip install ."  # install via setup.py by default
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python_version }}"
        cache: 'pip'

    - id: install-prefect
      run: |
        pip install prefect
        ${{ inputs.install_command }}
      shell: bash

    - id: login-prefect
      run: |
        prefect config set PREFECT_API_KEY=${{ inputs.prefect_api_key }}
        prefect config set PREFECT_API_URL=${{ inputs.prefect_api_url }}
      shell: bash

    - id: create-blocks
      run: python ${{ github.action_path }}/blocks.py -b $GITHUB_REF_NAME -r $GITHUB_SERVER_URL/$GITHUB_REPOSITORY -n ${{ inputs.block_name }} -i ${{ inputs.image_uri }} --region ${{ inputs.region }}
      shell: bash
