name: "Create Prefect blocks & GCP Infrastructure"
on:
  workflow_dispatch:
    inputs:
      region:
        description: GCP region
        required: true
        default: "us-east1"
        type: string
      zone:
        description: Zone in the selected GCP region
        required: true
        default: "us-east1-b"
        type: string
      artifact_repository:
        description: Artifact Registry Repository
        required: true
        default: "prefect"
        type: string
      image_name:
        description: Artifact Container Name for the Agent
        required: true
        default: "deployments"
        type: string
      runner_image_name:
        description: Artifact Container Name for the Runner
        required: true
        default: "runner"
        type: string
      machine_type:
        description: GCP Compute Engine instance type
        required: true
        default: "e2-micro"
        type: string
      block_name:
        description: "GitHub and CloudRunJob block name"
        required: false
        default: "default"
        type: string
      gcp_creds_block_name:
        description: "Name of the GcpCredentials block"
        required: false
        default: "default"
        type: string
      agent_docker_file_path:
        description: "Path to the Dockerfile to build image for the agent"
        required: false
        default: "config/agent/Dockerfile"
        type: string
      runner_docker_file_path:
        description: "Path to the Dockerfile to build image for the runner"
        required: false
        default: "config/runner/Dockerfile"
        type: string

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: deploy-agent-container
        uses: ./.github/actions/deploy-container
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          artifact_repository: ${{ github.event.inputs.artifact_repository }} # optional
          region: ${{ github.event.inputs.region }} # optional
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          #          gcp_sa_email: ${{ secrets.GCP_SA_EMAIL }}
          zone: ${{ github.event.inputs.zone }} # optional
          machine_type: ${{ github.event.inputs.machine_type }} # optional
          dockerfile_path: ${{ github.event.inputs.agent_docker_file_path }} # optional

      - id: build-runner-image
        uses: ./.github/actions/container-image
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          artifact_repository: ${{ github.event.inputs.artifact_repository }} # optional
          region: ${{ github.event.inputs.region }} # optional
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          #          gcp_sa_email: ${{ secrets.GCP_SA_EMAIL }}
          docker_file_path: ${{ github.event.inputs.runner_docker_file_path }} # optional
          image_name: ${{ github.event.inputs.runner_image_name }} # optional

      - id: create-blocks
        uses: ./.github/actions/blocks-quickstart
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          image_uri: ${{ env.IMAGE_URI }}
          block_name: ${{ github.event.inputs.block_name }} # optional
          region: ${{ github.event.inputs.region }} # optional
